spring.application.name=ids
spring.elasticsearch.uris=${ELASTIC_URL:http://elasticsearch:9200}
spring.elasticsearch.connection-timeout=5s
spring.elasticsearch.socket-timeout=30s
elasticsearch.url=http://elasticsearch:9200
abuseipdb.api.key=DEFAULT
virustotal.api.key=DEFAULT